const expenseActionTypes = {
    GET_EXPENSE_START: "GET_EXPENSE_START",
    GET_EXPENSE_SUCCESS: "GET_EXPENSE_SUCCESS",
    GET_EXPENSE_FAILURE: "GET_EXPENSE_FAILURE",
    CREATE_EXPENSE_START: "CREATE_EXPENSE_START",
    CREATE_EXPENSE_SUCCESS: "CREATE_EXPENSE_SUCCESS",
    CREATE_EXPENSE_FAILURE: "CREATE_EXPENSE_FAILURE",

  };
  
  export default expenseActionTypes;