const incomeActionTypes = {
    GET_INCOME_START: "GET_INCOME_START",
    GET_INCOME_SUCCESS: "GET_INCOME_SUCCESS",
    GET_INCOME_FAILURE: "GET_INCOME_FAILURE",
    CREATE_INCOME_START: "CREATE_INCOME_START",
    CREATE_INCOME_SUCCESS: "CREATE_INCOME_SUCCESS",
    CREATE_INCOME_FAILURE: "CREATE_INCOME_FAILURE",

  };
  
  export default incomeActionTypes;