const categoryActionTypes = {
    GET_CATEGORY_START: "GET_CATEGORY_START",
    GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
    GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
    CREATE_CATEGORY_START: "CREATE_CATEGORY_START",
    CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
    CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",

  };
  
  export default categoryActionTypes;