const loanActionTypes = {
    GET_LOAN_START: "GET_LOAN_START",
    GET_LOAN_SUCCESS: "GET_LOAN_SUCCESS",
    GET_LOAN_FAILURE: "GET_LOAN_FAILURE",
    CREATE_LOAN_START: "CREATE_LOAN_START",
    CREATE_LOAN_SUCCESS: "CREATE_LOAN_SUCCESS",
    CREATE_LOAN_FAILURE: "CREATE_LOAN_FAILURE",

  };
  
  export default loanActionTypes;